name: Build

on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
      
      - name: Test
        run: npm run test
      
    
